server:
  port: 28000
netty-websocket:
  port: 28001
  path: /ws
#websocket全地址
ws-url: ws://localhost:28001/ws
#http地址，如果多个服务器都部署了viewlog，其它地址设置为/viewlog/2，/viewlog/3 等等
http-path: /viewlog
#可以查看日志文件的范围-多少天以内的-默认查看10天内的日志文件
log-scope: 3
#配置要查看的日志路径：名称|日志路径
log-path:
  log1|D:\var\logs

spring:
  security:
    user:
      name: admin
      password: log@33
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  freemarker:
    suffix: .ftl
    content-type: text/html
    charset: UTF-8
    cache: false
    template-loader-path: classpath:/templates
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /static/**
