server:
  port: 26000
  use-forward-headers: true
  tomcat:
    protocol-header: X-Forwarded-Proto
    port-header: X-Forwarded-Port
  servlet:
    session:
      timeout: 60m
netty-websocket:
  port: 26001
  path: /ws
#是否需要登录验证
#spring:
#  security:
#    user:
#      name: admin
#      password: admin
threadPool:
  corePoolSize: 8
  maximumPoolSize: 32
  keepAliveTime: 3600
#服务监控
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always

